### ISSUE TITLE
[Feature]1.2.3のReleaseにログイン機能がない

### ISSUE THREAD

**Issue by konbraphat51** [niconicolibs/niconico.py#41]
本レポジトリにはNicoNicoクラスにlogin()が実装されていますが、pipでインストールできるreleaseにはその実装が抜けております。
login()の実装を含めてreleaseしていただけますでしょうか。

**Comment by Negima1072** [comment]
issueありがとうございます。
しばらく時間がなかったのでrepoを放置していました。
release致しましたのでご確認ください。
何か不具合・要望等ありましたらまたissueをお願いできればと思います。
