### ISSUE TITLE
非同期版を作る。

### ISSUE THREAD

**Issue by tasuren** [niconicolibs/niconico.py#7]
継承して置き換える。  
eg: `from niconico.aio import NicoNico`  
(開発優先順位は低い)

**Comment by tuna2134** [comment]
それ担当したい(アサインお願い)

**Comment by tasuren** [comment]
Ohk
コードスタイル崩さないでね。

**Comment by tuna2134** [comment]
了解

**Comment by tuna2134** [comment]
> Ohk
> コードスタイル崩さないでね。

ちなみにコードスタイルってpep8に従っていればいい？

**Comment by tasuren** [comment]
https://github.com/tasuren/niconico.py/blob/main/contributing.md
にある。

**Comment by tasuren** [comment]
もう全部非同期にしてしまおうかしら。

**Comment by tuna2134** [comment]
> もう全部非同期にしてしまおうかしら。

ああね

**Comment by tuna2134** [comment]
やろうとしたら、マジでごっそりと変わるんだよね

**Comment by tasuren** [comment]
あと、もし非同期と両方実装するんだったらhttpxに乗り換えようかな。
`pip install niconico.py[asynchronous]`とかしないで済む。

**Comment by tuna2134** [comment]
> あと、もし非同期と両方実装するんだったらhttpxに乗り換えようかな。
> `pip install niconico.py[asynchronous]`とかしないで済む。

httpxは僕は使っている()

**Comment by tasuren** [comment]
`asyncio.run`を使えば簡単に非同期で実行する事が出来るから、もう全て非同期でも良いように思える。
